server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.cloud.openfeign.client.config.bankClient.url=http://localhost:8080
spring.cloud.openfeign.client.config.bankClient.connectTimeout=5000
spring.cloud.openfeign.client.config.bankClient.readTimeout=5000